name: LeetMMO
version: ${project.version}
main: us.toh.leetmmo.LeetMMO
api-version: 1.16
authors: [ ctoh, atoh ]
description: This is some Leet Code for Leet MMO
commands:
  leetinfo:
    description: Get plugin information
    usage: /<command>
  leetstats:
    description: See current level
    usage: /<command>
  leetnskills:
    description: Open Normal Skill Tree GUI
    usage: /<command>
  leetfarming:
    description: Farming skills
    usage: /<command>
  leetmining:
    description: Mining skills
    usage: /<command>